# Site settings
title: Kevin Glueck
email: kglueck@gmail.com
url: http://www.babblefish.net
description: "Custom integrator of home automation tools.  Python/Ruby/Shell Scripting, OpenSprinkler, Proliphix/Nest/Honeywell, Geist/IT Watchdogs"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Kevin Glueck

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/kglueck
  - title: twitter
    url: https://twitter.com/kglueck
  - title: linkedin
    url: https://www.linkedin.com/in/knglueck

# Build settings
markdown: kramdown
permalink: pretty
